spring.application.name=hello-world

spring.datasource.url=${DB_URL:jdbc:postgresql://192.168.0.37:5432/helloworld?currentSchema=my_schema}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
