spring.application.name=hello-world
server.port=${SERVER_PORT:8080}
spring.profiles.active=${PROFILES:local}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

spring.r2dbc.url=${R2DBC_URL}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:abcdefghijklmnopqrstuvwxyz123456}

services.account.url=http://account-api:8081
services.order.url=http://order-api:8082
services.market.url=http://market-data-api:8083

spring.main.web-application-type=reactive